[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "programs/asset_controller",
  "programs/data_registry",
  "programs/identity_registry",
  "programs/policy_engine",
]

[programs.localnet]
asset_controller = "2fJZj6eLMvdGkHTePvbXGjh9x1hHSMvkBPhTcAAPvBMa"
data_registry = "8Bp1xoRscjuHoG1KT41zAaujGTx2fyB2uzTt8GTeWZX8"
identity_registry = "7Zis9Cg1pa3PMRCMfJBgzoQThoBA21QMrkmEnx6nZdQQ"
policy_engine = "4wyusm2nxncvNyiVej5mZ1k1mVPhfG41oNvHx4BWiYMq"

[scripts]
test = "cd clients/rwa-token-sdk && yarn test"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[toolchain]
anchor_version = "0.30.1"